var tree = [["Eloquent",,"",
                [["Pathogen","Eloquent\/Pathogen.html","",
                [["Exception","Eloquent\/Pathogen\/Exception.html","",
                [["AbstractInvalidPathAtomException","Eloquent\/Pathogen\/Exception\/AbstractInvalidPathAtomException.html"," < Exception",
                [        ]],["EmptyPathAtomException","Eloquent\/Pathogen\/Exception\/EmptyPathAtomException.html"," < AbstractInvalidPathAtomException",
                [        ]],["EmptyPathException","Eloquent\/Pathogen\/Exception\/EmptyPathException.html"," < Exception",
                [        ]],["InvalidPathAtomCharacterException","Eloquent\/Pathogen\/Exception\/InvalidPathAtomCharacterException.html"," < AbstractInvalidPathAtomException",
                [        ]],["InvalidPathAtomExceptionInterface","Eloquent\/Pathogen\/Exception\/InvalidPathAtomExceptionInterface.html","",
                [        ]],["InvalidPathStateException","Eloquent\/Pathogen\/Exception\/InvalidPathStateException.html"," < Exception",
                [        ]],["PathAtomContainsSeparatorException","Eloquent\/Pathogen\/Exception\/PathAtomContainsSeparatorException.html"," < AbstractInvalidPathAtomException",
                [        ]],["UndefinedPathAtomException","Eloquent\/Pathogen\/Exception\/UndefinedPathAtomException.html"," < Exception",
                [        ]]        ]],["Factory","Eloquent\/Pathogen\/Factory.html","",
                [["PathFactory","Eloquent\/Pathogen\/Factory\/PathFactory.html","",
                [        ]],["PathFactoryInterface","Eloquent\/Pathogen\/Factory\/PathFactoryInterface.html","",
                [        ]]        ]],["FileSystem","Eloquent\/Pathogen\/FileSystem.html","",
                [["Factory","Eloquent\/Pathogen\/FileSystem\/Factory.html","",
                [["AbstractFileSystemPathFactory","Eloquent\/Pathogen\/FileSystem\/Factory\/AbstractFileSystemPathFactory.html","",
                [        ]],["FileSystemPathFactory","Eloquent\/Pathogen\/FileSystem\/Factory\/FileSystemPathFactory.html"," < AbstractFileSystemPathFactory",
                [        ]],["FileSystemPathFactoryInterface","Eloquent\/Pathogen\/FileSystem\/Factory\/FileSystemPathFactoryInterface.html","",
                [        ]],["PlatformFileSystemPathFactory","Eloquent\/Pathogen\/FileSystem\/Factory\/PlatformFileSystemPathFactory.html"," < AbstractFileSystemPathFactory",
                [        ]]        ]],["Normalizer","Eloquent\/Pathogen\/FileSystem\/Normalizer.html","",
                [["FileSystemPathNormalizer","Eloquent\/Pathogen\/FileSystem\/Normalizer\/FileSystemPathNormalizer.html","",
                [        ]]        ]],["Resolver","Eloquent\/Pathogen\/FileSystem\/Resolver.html","",
                [["WorkingDirectoryResolver","Eloquent\/Pathogen\/FileSystem\/Resolver\/WorkingDirectoryResolver.html"," < BoundPathResolver",
                [        ]]        ]],["AbsoluteFileSystemPathInterface","Eloquent\/Pathogen\/FileSystem\/AbsoluteFileSystemPathInterface.html","",
                [        ]],["AbstractAbsoluteFileSystemPath","Eloquent\/Pathogen\/FileSystem\/AbstractAbsoluteFileSystemPath.html"," < AbsolutePath",
                [        ]],["AbstractRelativeFileSystemPath","Eloquent\/Pathogen\/FileSystem\/AbstractRelativeFileSystemPath.html"," < RelativePath",
                [        ]],["FileSystemPathInterface","Eloquent\/Pathogen\/FileSystem\/FileSystemPathInterface.html","",
                [        ]],["RelativeFileSystemPathInterface","Eloquent\/Pathogen\/FileSystem\/RelativeFileSystemPathInterface.html","",
                [        ]]        ]],["Normalizer","Eloquent\/Pathogen\/Normalizer.html","",
                [["PathNormalizer","Eloquent\/Pathogen\/Normalizer\/PathNormalizer.html","",
                [        ]],["PathNormalizerInterface","Eloquent\/Pathogen\/Normalizer\/PathNormalizerInterface.html","",
                [        ]]        ]],["Resolver","Eloquent\/Pathogen\/Resolver.html","",
                [["BoundPathResolver","Eloquent\/Pathogen\/Resolver\/BoundPathResolver.html","",
                [        ]],["BoundPathResolverInterface","Eloquent\/Pathogen\/Resolver\/BoundPathResolverInterface.html","",
                [        ]],["NormalizingPathResolver","Eloquent\/Pathogen\/Resolver\/NormalizingPathResolver.html","",
                [        ]],["PathResolver","Eloquent\/Pathogen\/Resolver\/PathResolver.html","",
                [        ]],["PathResolverInterface","Eloquent\/Pathogen\/Resolver\/PathResolverInterface.html","",
                [        ]]        ]],["Unix","Eloquent\/Pathogen\/Unix.html","",
                [["Factory","Eloquent\/Pathogen\/Unix\/Factory.html","",
                [["UnixPathFactory","Eloquent\/Pathogen\/Unix\/Factory\/UnixPathFactory.html"," < PathFactory",
                [        ]]        ]],["AbsoluteUnixPath","Eloquent\/Pathogen\/Unix\/AbsoluteUnixPath.html"," < AbstractAbsoluteFileSystemPath",
                [        ]],["AbsoluteUnixPathInterface","Eloquent\/Pathogen\/Unix\/AbsoluteUnixPathInterface.html","",
                [        ]],["RelativeUnixPath","Eloquent\/Pathogen\/Unix\/RelativeUnixPath.html"," < AbstractRelativeFileSystemPath",
                [        ]],["RelativeUnixPathInterface","Eloquent\/Pathogen\/Unix\/RelativeUnixPathInterface.html","",
                [        ]],["UnixPathInterface","Eloquent\/Pathogen\/Unix\/UnixPathInterface.html","",
                [        ]]        ]],["Windows","Eloquent\/Pathogen\/Windows.html","",
                [["Exception","Eloquent\/Pathogen\/Windows\/Exception.html","",
                [["DriveMismatchException","Eloquent\/Pathogen\/Windows\/Exception\/DriveMismatchException.html"," < Exception",
                [        ]],["InvalidDriveSpecifierException","Eloquent\/Pathogen\/Windows\/Exception\/InvalidDriveSpecifierException.html"," < Exception",
                [        ]]        ]],["Factory","Eloquent\/Pathogen\/Windows\/Factory.html","",
                [["WindowsPathFactory","Eloquent\/Pathogen\/Windows\/Factory\/WindowsPathFactory.html"," < PathFactory",
                [        ]],["WindowsPathFactoryInterface","Eloquent\/Pathogen\/Windows\/Factory\/WindowsPathFactoryInterface.html","",
                [        ]]        ]],["Normalizer","Eloquent\/Pathogen\/Windows\/Normalizer.html","",
                [["WindowsPathNormalizer","Eloquent\/Pathogen\/Windows\/Normalizer\/WindowsPathNormalizer.html"," < PathNormalizer",
                [        ]]        ]],["AbsoluteWindowsPath","Eloquent\/Pathogen\/Windows\/AbsoluteWindowsPath.html"," < AbstractAbsoluteFileSystemPath",
                [        ]],["AbsoluteWindowsPathInterface","Eloquent\/Pathogen\/Windows\/AbsoluteWindowsPathInterface.html","",
                [        ]],["RelativeWindowsPath","Eloquent\/Pathogen\/Windows\/RelativeWindowsPath.html"," < AbstractRelativeFileSystemPath",
                [        ]],["RelativeWindowsPathInterface","Eloquent\/Pathogen\/Windows\/RelativeWindowsPathInterface.html","",
                [        ]],["WindowsPathInterface","Eloquent\/Pathogen\/Windows\/WindowsPathInterface.html","",
                [        ]]        ]],["AbsolutePath","Eloquent\/Pathogen\/AbsolutePath.html"," < AbstractPath",
                [        ]],["AbsolutePathInterface","Eloquent\/Pathogen\/AbsolutePathInterface.html","",
                [        ]],["AbstractPath","Eloquent\/Pathogen\/AbstractPath.html","",
                [        ]],["PathInterface","Eloquent\/Pathogen\/PathInterface.html","",
                [        ]],["RelativePath","Eloquent\/Pathogen\/RelativePath.html"," < AbstractPath",
                [        ]],["RelativePathInterface","Eloquent\/Pathogen\/RelativePathInterface.html","",
                [        ]]        ]]        ]]        ]

